name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yml
  dependencies:
    uses: ./.github/workflows/dependencies.yml
  test:
    uses: ./.github/workflows/test.yml
