name: Test

on:
  pull_request:
    paths:
      - '**.rs'
      - '**Cargo.toml'
  merge_group:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v5
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@cargo-nextest
      - run: sudo apt install -y libwayland-dev wayland-protocols
      - run: cargo nextest run --workspace --locked

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: SebRollen/toml-action@v1.0.2
        id: msrv
        with:
          file: 'Cargo.toml'
          field: 'workspace.package.rust-version'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.msrv.outputs.value }}
      - uses: taiki-e/install-action@cargo-nextest
      - run: sudo apt install -y libwayland-dev wayland-protocols
      - run: cargo nextest run --workspace --locked
