name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests
        run: cargo llvm-cov --workspace --locked nextest --html
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: target/nextest/default/report.xml
          retention-days: 30
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: target/llvm-cov/
          retention-days: 30

  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-nextest
      - run: cargo build --workspace --locked --verbose
      - run: cargo nextest run --workspace --locked

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: SebRollen/toml-action@v1.0.2
        id: msrv
        with:
          file: 'Cargo.toml'
          field: 'package.rust-version'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.msrv.outputs.value }}
      - uses: taiki-e/install-action@cargo-nextest
      - run: cargo build --workspace --locked --verbose
      - run: cargo nextest run --workspace --locked
